# Generated by Django 5.2 on 2025-04-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreempleado', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('antiguedad', models.IntegerField()),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
    ]
